title: Home
author:
  name: Jeroen Visser
description: My personal space on the internet. This is where I write stuff for total strangers. Feel free to browse.
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
  - archive.md

minima:
  skin: dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/VisserJ"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/jeroen-visser/"
