title: Jeroen's Blog
author:
  name: Jeroen Visser
description: This is where I write stuff for internet strangers.
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md

minima:
  skin: dark
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/VisserJ"
