title: "Jeroen's Blog"
author: "Jeroen Visser"
description: "Where I tell stuff to internet strangers."

#email: "example@mail.com"
#twitter_username: "twitteruser"
github_username: "VisserJ"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

remote_theme: jekyll/minima

minima:
  skin: dark

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
